### ISSUE TITLE
Minesweeper game issue.

### ISSUE THREAD

**Issue by Leos-Khai** [Amerikranian/Arcade#12]
In the file src/games/minesweeper.py, it says this line has issue:
`match self.grid[index]:`
From what i searched online, the code seems to be correct. but running main.py points me to that issue.

**Comment by amerikrainian** [comment]
Are you on Python 3.10? Match syntax was introduced in this version

That being said, I removed the statements because Nuitka could not parse them. You'll still need 3.10 for logging capabilities though, so I suggest updating and seeing if you still have problems. I'll keep this open for a bit in case you do run into trouble with the new version.

**Comment by Leos-Khai** [comment]
Ah right... 3.10 is different from 3.1. Thanks lol.
